### ISSUE TITLE
Card creation process doesn't consider duplication

### ISSUE THREAD

**Issue by funamioh** [NHV33/kanji_cam#49]
As Is:
- When kanji is scanned, it creates a new card even if there is a card with same kanji exists

To Be:
- If the same kanji already exists in card, it redirect to card show page and display message like "nice to see you again! (?)"

**Comment by NHV33** [comment]
Thanks. I am addressing this issue in the following pull request:
https://github.com/NHV33/kanji_cam/pull/55
